const KEY='construction_erp_canvas_v4';
const empty={projects:[],boq:[],ledger:[],suppliers:[],inventory:[],automationLog:[]};
let state=load();
function load(){try{return JSON.parse(localStorage.getItem(KEY))||structuredClone(empty)}catch{return structuredClone(empty)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function id(){return Date.now()+Math.floor(Math.random()*9999)}
function val(i){return document.getElementById(i)?.value||''}
function setv(i,v){const el=document.getElementById(i);if(el)el.value=v??''}
function money(v){return new Intl.NumberFormat('ar-EG',{maximumFractionDigits:0}).format(Number(v||0))}
function norm(v){return String(v||'').toLowerCase()}
function match(o,q){q=norm(q);return !q||Object.values(o).some(v=>norm(v).includes(q))}
function pName(pid){return state.projects.find(p=>String(p.id)===String(pid))?.name||'عام'}
function projectById(pid){return state.projects.find(p=>String(p.id)===String(pid))}
function sum(t){return state.ledger.filter(x=>x.type===t).reduce((s,x)=>s+Number(x.amount||0),0)}
function typeLabel(t){return ({building:'مباني',road:'طرق',tank:'خزانات',warehouse:'هناجر ومخازن',factory:'مصانع'}[t]||'عام')}
function projectBoqTotal(pid){return state.boq.filter(b=>String(b.project)===String(pid)).reduce((s,b)=>s+Number(b.qty||0)*Number(b.cost||0),0)}
function projectRevenue(pid){return state.ledger.filter(l=>String(l.project)===String(pid)&&l.type==='revenue').reduce((s,l)=>s+Number(l.amount||0),0)}
function projectExpense(pid){return state.ledger.filter(l=>String(l.project)===String(pid)&&l.type==='expense').reduce((s,l)=>s+Number(l.amount||0),0)}
const templates={
 building:{boq:[['أعمال الحفر','م3',0.35,8],['خرسانة عادية','م3',0.08,95],['خرسانة مسلحة','م3',0.22,145],['حديد تسليح','طن',0.018,820],['بلوك ومباني','م2',1.2,18],['لياسة ودهانات','م2',1.8,12]],suppliers:[['مورد الخرسانة','خرسانة'],['مورد الحديد','حديد'],['مقاول تشطيبات','تشطيبات']],inventory:[['حديد تسليح','طن',0.018,10,820],['اسمنت','كيس',0.55,100,8],['بلوك','حبة',8,500,0.45]]},
 road:{boq:[['تسوية الموقع','م2',1,1.8],['طبقة أساس','م3',0.18,22],['أسفلت','طن',0.12,75],['بردورات','متر',0.25,9],['تصريف أمطار','متر',0.06,45]],suppliers:[['مورد الأسفلت','أسفلت'],['مورد معدات طرق','معدات'],['مورد حصى ومواد أساس','مواد خام']],inventory:[['أسفلت','طن',0.12,20,75],['حصى أساس','م3',0.18,50,22],['ديزل معدات','لتر',2,300,1.1]]},
 tank:{boq:[['حفر خزان','م3',0.55,9],['خرسانة قاعدة','م3',0.18,140],['خرسانة جدران','م3',0.28,155],['عزل مائي','م2',1.6,12],['اختبار وتسليم','وحدة',1,800]],suppliers:[['مورد مواد العزل','عزل'],['مورد الخرسانة','خرسانة'],['مورد مضخات','معدات']],inventory:[['مواد عزل','م2',1.6,100,12],['حديد تسليح','طن',0.02,8,820],['إضافات خرسانة','لتر',0.7,50,4]]},
 warehouse:{boq:[['قواعد خرسانية','م3',0.12,135],['هيكل معدني','طن',0.035,1250],['ألواح تغطية','م2',1.1,16],['أرضيات خرسانية','م2',1,18],['أبواب صناعية','وحدة',0.01,1500]],suppliers:[['مورد الهياكل المعدنية','حديد'],['مورد ألواح ساندوتش','تغطيات'],['مقاول أرضيات','خرسانة']],inventory:[['حديد إنشائي','طن',0.035,5,1250],['ألواح تغطية','م2',1.1,200,16],['براغي ومثبتات','كجم',0.3,50,3]]},
 factory:{boq:[['أعمال مدنية','م2',1,65],['هيكل معدني','طن',0.04,1250],['كهرباء صناعية','م2',1,22],['شبكات مياه وصرف','متر',0.3,35],['أرضيات إيبوكسي','م2',1,28],['اختبارات وتشغيل','وحدة',1,2500]],suppliers:[['مورد معدات صناعية','معدات'],['مورد كهرباء','كهرباء'],['مورد أرضيات صناعية','تشطيبات']],inventory:[['كابلات كهرباء','متر',1.5,200,3.5],['مواسير','متر',0.3,80,6],['دهان إيبوكسي','كجم',0.4,60,7]]}
};
function autoCreateProject(){const name=val('aName')||'مشروع مؤتمت';const client=val('aClient')||'عميل';const type=val('aType')||'building';const value=Number(val('aValue')||1000000);const area=Number(val('aArea')||1000);const start=val('aStart')||new Date().toISOString().slice(0,10);const project={id:id(),name,client,type,value,area,start,progress:0,status:'active',auto:true};state.projects.unshift(project);const tpl=templates[type]||templates.building;tpl.boq.forEach(row=>state.boq.unshift({id:id(),project:project.id,item:row[0],unit:row[1],qty:round(area*row[2]),cost:row[3],auto:true}));tpl.suppliers.forEach(row=>{if(!state.suppliers.some(s=>s.name===row[0]&&String(s.project)===String(project.id)))state.suppliers.unshift({id:id(),name:row[0],cat:row[1],phone:'',address:'',project:project.id,auto:true})});tpl.inventory.forEach(row=>state.inventory.unshift({id:id(),name:row[0],unit:row[1],qty:round(area*row[2]),min:row[3],cost:row[4],project:project.id,auto:true}));const boqTotal=projectBoqTotal(project.id);state.ledger.unshift({id:id(),type:'expense',project:project.id,desc:'تكلفة تقديرية مولدة من BOQ',amount:round(boqTotal),date:start,auto:true});state.ledger.unshift({id:id(),type:'revenue',project:project.id,desc:'دفعة مقدمة تلقائية 20%',amount:round(value*0.2),date:start,auto:true});state.automationLog.unshift({id:id(),date:new Date().toLocaleString('ar-EG'),project:project.id,message:`تم توليد ${tpl.boq.length} بنود BOQ و ${tpl.suppliers.length} موردين و ${tpl.inventory.length} مواد مخزون وربطها بالمشروع`});save();render();showPage('dashboard');toast('تم توليد وربط المشروع تلقائيًا')}
function round(v){return Math.round(Number(v||0)*100)/100}
function seedData(){state=structuredClone(empty);setv('aName','مشروع مبنى إداري مؤتمت');setv('aClient','شركة تجريبية');setv('aType','building');setv('aValue','2500000');setv('aArea','1500');autoCreateProject();setv('aName','مشروع خزانات مياه مؤتمت');setv('aClient','جهة حكومية');setv('aType','tank');setv('aValue','1200000');setv('aArea','800');autoCreateProject();toast('تم توليد بيانات مؤتمتة')}
function render(){renderKpis();renderProjects();renderBoq();renderFinance();renderSuppliers();renderInventory();renderReports();renderAutomationLog()}
function renderKpis(){const revenue=sum('revenue'),expense=sum('expense'),contract=state.projects.reduce((s,p)=>s+Number(p.value||0),0);const boqTotal=state.boq.reduce((s,b)=>s+Number(b.qty||0)*Number(b.cost||0),0);const k=[['المشاريع',state.projects.length],['قيمة العقود',money(contract)],['BOQ إجمالي',money(boqTotal)],['الإيرادات',money(revenue)],['المصروفات',money(expense)],['صافي الربح',money(revenue-expense)],['الموردون',state.suppliers.length],['المخزون',state.inventory.length]];document.getElementById('kpis').innerHTML=k.map(x=>`<div class="card kpi"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');const max=Math.max(1,...state.ledger.map(x=>Math.abs(Number(x.amount||0))));document.getElementById('bars').innerHTML=state.ledger.map(x=>`<div class="bar ${x.type==='expense'?'exp':''}" style="height:${Math.max(15,Math.round(Math.abs(x.amount)/max*185))}px"><small>${x.type==='expense'?'مصروف':'إيراد'}</small></div>`).join('')||'<div class="empty">لا توجد حركات</div>';document.getElementById('profit').innerHTML=`<p>إجمالي العقود: <b>${money(contract)}</b></p><p>BOQ: <b>${money(boqTotal)}</b></p><p>الإيرادات: <b>${money(revenue)}</b></p><p>المصروفات: <b>${money(expense)}</b></p><p>صافي الربح: <b>${money(revenue-expense)}</b></p>`;document.getElementById('dashRows').innerHTML=state.projects.slice(0,6).map(p=>`<tr><td>${p.name}</td><td>${typeLabel(p.type)}</td><td>${money(p.value)}</td><td>${money(projectBoqTotal(p.id))}</td><td>${money(Number(p.value||0)-projectBoqTotal(p.id))}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">لا توجد مشاريع</td></tr>'}
function renderProjects(){const q=val('projectSearch');document.getElementById('projectRows').innerHTML=state.projects.filter(p=>match({...p,typeAr:typeLabel(p.type)},q)).map(p=>`<tr><td>${p.name}</td><td>${typeLabel(p.type)}</td><td>${p.client}</td><td>${money(p.value)}</td><td>${money(projectBoqTotal(p.id))}</td><td><button class="btn red" onclick="deleteLinkedProject(${p.id})">حذف مترابط</button></td></tr>`).join('')||'<tr><td colspan="6" class="empty">لا توجد نتائج</td></tr>'}
function renderBoq(){const q=val('boqSearch');document.getElementById('boqRows').innerHTML=state.boq.filter(b=>match({...b,projectName:pName(b.project)},q)).map(b=>`<tr><td>${pName(b.project)}</td><td>${b.item}</td><td>${b.unit}</td><td>${money(b.qty)}</td><td>${money(b.cost)}</td><td>${money(Number(b.qty)*Number(b.cost))}</td><td><button class="btn red" onclick="del('boq',${b.id})">حذف</button></td></tr>`).join('')||'<tr><td colspan="7" class="empty">لا توجد نتائج</td></tr>'}
function renderFinance(){const q=val('ledgerSearch');document.getElementById('ledgerRows').innerHTML=state.ledger.filter(l=>match({...l,projectName:pName(l.project)},q)).map(l=>`<tr><td>${l.type==='revenue'?'إيراد':'مصروف'}</td><td>${pName(l.project)}</td><td>${l.desc}</td><td>${money(l.amount)}</td><td>${l.date||'-'}</td><td><button class="btn red" onclick="del('ledger',${l.id})">حذف</button></td></tr>`).join('')||'<tr><td colspan="6" class="empty">لا توجد نتائج</td></tr>'}
function renderSuppliers(){const q=val('supplierSearch');document.getElementById('supplierRows').innerHTML=state.suppliers.filter(s=>match({...s,projectName:pName(s.project)},q)).map(s=>`<tr><td>${s.name}</td><td>${s.cat}</td><td>${s.phone||'-'}</td><td>${pName(s.project)}</td><td><button class="btn red" onclick="del('suppliers',${s.id})">حذف</button></td></tr>`).join('')||'<tr><td colspan="5" class="empty">لا توجد نتائج</td></tr>'}
function renderInventory(){const q=val('inventorySearch');document.getElementById('inventoryRows').innerHTML=state.inventory.filter(i=>match({...i,projectName:pName(i.project)},q)).map(i=>`<tr><td>${i.name}</td><td>${i.unit}</td><td>${money(i.qty)}</td><td>${money(i.min)}</td><td>${money(i.cost)}</td><td>${pName(i.project)}</td><td><button class="btn red" onclick="del('inventory',${i.id})">حذف</button></td></tr>`).join('')||'<tr><td colspan="7" class="empty">لا توجد نتائج</td></tr>'}
function renderReports(){const linked=state.projects.map(p=>({p,boq:state.boq.filter(b=>String(b.project)===String(p.id)).length,ledger:state.ledger.filter(l=>String(l.project)===String(p.id)).length,suppliers:state.suppliers.filter(s=>String(s.project)===String(p.id)).length,inventory:state.inventory.filter(i=>String(i.project)===String(p.id)).length}));document.getElementById('reportSummary').innerHTML=linked.map(x=>`<p><b>${x.p.name}</b>: BOQ ${x.boq} | مالية ${x.ledger} | موردين ${x.suppliers} | مخزون ${x.inventory}</p>`).join('')||'<p class="empty">لا توجد بيانات</p>'}
function renderAutomationLog(){const el=document.getElementById('automationLog');if(!el)return;el.innerHTML=state.automationLog.slice(0,5).map(x=>`<p><b>${x.date}</b><br>${x.message}<br><span class="linked">${pName(x.project)}</span></p>`).join('')||'<p class="empty">لم يتم تنفيذ أتمتة بعد</p>'}
function saveProject(){const p={id:id(),name:val('pName')||'مشروع يدوي',client:val('pClient')||'',type:val('pType')||'building',value:Number(val('pValue')||0),progress:Number(val('pProgress')||0),status:val('pStatus')||'active',auto:false};state.projects.unshift(p);save();render();toast('تم حفظ المشروع اليدوي')}
function clearProjectForm(){['pName','pClient','pValue','pProgress'].forEach(x=>setv(x,''));setv('pType','building');setv('pStatus','active')}
function del(list,itemId){if(confirm('تأكيد الحذف؟')){state[list]=state[list].filter(x=>Number(x.id)!==Number(itemId));save();render();toast('تم الحذف')}}
function deleteLinkedProject(pid){if(!confirm('سيتم حذف المشروع وكل البيانات المرتبطة به. متابعة؟'))return;state.projects=state.projects.filter(x=>Number(x.id)!==Number(pid));['boq','ledger','suppliers','inventory'].forEach(list=>state[list]=state[list].filter(x=>Number(x.project)!==Number(pid)));save();render();toast('تم حذف المشروع والبيانات المرتبطة')}
function resetAll(){if(confirm('هل تريد مسح كل البيانات؟')){state=structuredClone(empty);save();render();toast('تم مسح البيانات')}}
function exportJson(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='construction-erp-linked-v4.json';a.click();toast('تم تصدير النسخة الاحتياطية')}
document.getElementById('importFile').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{state=JSON.parse(r.result);save();render();toast('تم الاستيراد')}catch{toast('ملف غير صالح')}};r.readAsText(f)});
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.style.display='block';setTimeout(()=>t.style.display='none',2200)}
function showPage(page){document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));document.querySelectorAll('.page').forEach(p=>p.classList.add('hide'));document.getElementById(page).classList.remove('hide');document.getElementById('title').textContent=document.querySelector(`[data-page="${page}"]`)?.textContent||'لوحة التحكم'}
document.getElementById('nav').addEventListener('click',e=>{if(e.target.tagName==='BUTTON')showPage(e.target.dataset.page)});
if(!localStorage.getItem(KEY))seedData();else render();
